name: Core-API | Build and deploy

on:
  workflow_call:
    inputs:
      version:
        description: 'The version of the new build.'
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up to JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          cache: 'maven'
          java-version: 8

      - name: Load maven dependencies
        run: mvn -B dependency:go-offline

      - name: Set Project Version
        run: mvn versions:set -DnewVersion=1.234-SNAPSHOT

      - name: Build with Maven
        run: mvn -B clean package

      - name: Deploy to GitHub Packages # Repository is set in pom.xml
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
