name: Core-API | Build and deploy

on:
  workflow_call:
    inputs:
      version:
        description: 'The version of the new build.'
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up to JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          cache: 'maven'
          java-version: 8

      - name: Set Project Version
        run: mvn versions:set -DnewVersion=${{ inputs.version }}

      - name: Build with Maven with classifier
        if: github.event_name != 'release'
        run: mvn -B clean package -Dproject.classifier=$GITHUB_REF_NAME

      - name: Build with Maven without classifier (only on Release)
        if: github.event_name == 'release'
        run: mvn -B clean package

      - name: Deploy to GitHub Packages # Repository is set in pom.xml
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
