name: Core-API | Build and deploy

on:
  workflow_call:
    inputs:
      version:
        description: 'The version of the new build.'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up to JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          cache: 'maven'
          java-version: 8

      - name: Build with Maven
        run: mvn source:jar -DapiVersion=${{ inputs.version }}

      - name: Deploy to GitHub Packages # Repository is set in pom.xml
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
