name: Core-API | Nightly Builder

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true
        type: string

jobs:
  get-version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version-push.outputs.version || steps.set-version.outputs.version }}
    steps:
      - name: Set short commit hash on push
        if: github.event_name == 'push'
        id: set-version-push
        run: echo ::set-output name=version::$(git rev-parse --short HEAD)
      - name: Set version from input
        if: github.event_name == 'workflow_dispatch'
        id: set-version
        run: echo ::set-output name=version::${{ github.event.inputs.version }}

  build-nightly:
    name: Build Nightly version
    needs: get-version
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.get-version.outputs.version }}
