name: Core-API | Nightly Builder

on:
  push:
    branches-ignore:
      - master
      - main

  workflow_dispatch:

jobs:
  get-latest-version:
    name: Get latest version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.increment-version.outputs.release }}
    steps:
      - name: Get latest release version
        if: github.event_name == 'push'
        id: get-latest-version
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          repository: ${{ github.repository }}

      - name: Increment version
        if: github.event_name == 'push'
        id: increment-version
        run: |
          RELEASE_NAME=${{ steps.get-latest-version.outputs.release }}
          echo "release=$(echo ${RELEASE_NAME#v} | awk -F. -v OFS=. '{$NF = $NF + 1;} 1')" >> "$GITHUB_OUTPUT"

  build-nightly:
    name: Build Nightly version
    needs: get-latest-version
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.get-latest-version.outputs.version }}-SNAPSHOT
